repos:
- repo: https://github.com/asottile/seed-isort-config
  rev: v2.2.0
  hooks:
  - id: seed-isort-config

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
  - id: isort
    args:
    - --multi-line=3
    - --trailing-comma
    - --force-grid-wrap=0
    - --combine-as
    - --line-width=88

- repo: https://github.com/ambv/black
  rev: 24.1.1
  hooks:
  - id: black

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  - id: mypy
    args:
    - --ignore-missing-imports
    - --warn-unused-configs
    - --disallow-untyped-defs
    - --disallow-incomplete-defs
    - --check-untyped-defs
    - --disallow-untyped-decorators
    - --no-implicit-optional
    - --warn-redundant-casts
    - --warn-unused-ignores
    - --warn-return-any
    exclude: ^docs/

- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    args:
    - --max-line-length=80
    - --select=C,E,F,W,B,B950
    - --ignore=E501,W503,E203
