repos:
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.5.0
  hooks:
  - id: seed-isort-config

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort
    args:
    - --multi-line=3
    - --trailing-comma
    - --force-grid-wrap=0
    - --combine-as
    - --line-width=88

- repo: https://github.com/ambv/black
  rev: 18.9b0
  hooks:
  - id: black
    language_version: python3.7

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.670
  hooks:
  - id: mypy
    args:
    - --ignore-missing-imports
    - --warn-unused-configs
    - --disallow-untyped-defs
    - --disallow-incomplete-defs
    - --check-untyped-defs
    - --disallow-untyped-decorators
    - --no-implicit-optional
    - --warn-redundant-casts
    - --warn-unused-ignores
    - --warn-return-any
    exclude: ^docs/

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: flake8
    args:
    - --max-line-length=80
    - --select=C,E,F,W,B,B950
    - --ignore=E501,W503,E203
